### ISSUE TITLE
Won't Scan/Discover Anything - Ubunut 22.04LTS

### ISSUE THREAD

**Issue by NikeLaosClericus** [lesleyxyz/node-tile#2]
https://github.com/abandonware/noble/issues/136

Looks like Noble is broken for newer Linux releases.

I ran:
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

**Comment by lesleyxyz** [comment]
Hello,

Do you have multiple USB Bluetooth adapters?
What distro & version of linux are you running?
It works for me on Debian 11 / Linux Kernel 6.3.2

Here are some troubleshooting steps:

Can you try to run `sudo node example.js` (as root)
Can you also share what you see when you run `DEBUG="*" node example.js`

Can you confirm the following command returns a device:
```bash
sudo hcitool dev
```

And this command returns your bluetooth device:
```bash
sudo lsusb
```

If all is OK, can you try to manually scan for bluetooth devices like such:
```bash
sudo hcitool scan
```

**Comment by NikeLaosClericus** [comment]
Laptop with one BT adapter built-in.
Ubuntu 22.04LTS - Linux Kernel 6.2.6
No difference running as root (sudo)

```
sudo hcitool dev
Devices:
	hci0	F4:7B:09:7E:3A:46
```
```

sudo lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 006: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 006 Device 005: ID 0bda:0411 Realtek Semiconductor Corp. Hub
Bus 006 Device 004: ID 17ef:30b8 Lenovo USB3.1 Hub             
Bus 006 Device 003: ID 17ef:30b6 Lenovo USB3.1 Hub             
Bus 006 Device 002: ID 8087:0b40 Intel Corp. USB3.0 Hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 008: ID 17ef:30bb Lenovo ThinkPad Thunderbolt 4 Dock USB Audio
Bus 003 Device 007: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 003 Device 006: ID 17ef:30b9 Lenovo USB2.0 Hub             
Bus 003 Device 005: ID 17ef:30b7 Lenovo USB2.0 Hub             
Bus 003 Device 004: ID 17ef:30b5 Lenovo 40B0
Bus 003 Device 003: ID 17ef:30b4 Lenovo ThinkPad Thunderbolt 4 Dock MCU Controller2
Bus 003 Device 002: ID 17ef:30ba Lenovo V1003
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 004: ID 06cb:00bd Synaptics, Inc. Prometheus MIS Touch Fingerprint Reader
Bus 004 Device 003: ID 5986:9106 Acer, Inc Integrated Camera
Bus 004 Device 005: ID 8087:0026 Intel Corp. AX201 Bluetooth
Bus 004 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

```
sudo hcitool scan
Scanning ...
	90:C7:D8:5B:9A:82	Z3201
	60:E3:2B:CA:C0:04	PATLPT24
	6A:E6:4A:00:10:A8	HT-SB30D SHARP
```
Those all seem fine?


And the State Change - poweredOn fires, as I do see console output "scanning"
```
noble.on('stateChange', state => {
	if (state === 'poweredOn'){
		noble.startScanning([], true);
                console.log("Scanning");
	}
}
```
But I never see actual scan start or discover:
```
noble.on("scanStart", state => {
    console.log(`scan: ${state}`);
})

noble.on("discover", state => {
    console.log(`discover: ${state}`);
})
```

What's interesting is that I will see scanStart fire, if I open my system bluetooth settings window while example is running, so noble can _see_ a scan start, but just can't initiate?

**Comment by lesleyxyz** [comment]
Okay thank you for all that information.
I just added support for [node-ble](https://github.com/chrvadala/node-ble) which is better maintained.
Now anyone can chose between either that and noble.

Could you update node-tile to the latest version (1.1.0) and test the **new** example.js please?
This should be using the new bluetooth library.

Do note that (for me) both libraries sometimes hang on the "preAuth" step, rerunning the program should work then.
Let me know :)

node-ble requires dbus & bluez:
```bash
sudo apt-get install dbus bluez
```

You will also need to configure dbus by creating a file at `/etc/dbus-1/system.d/node-ble.conf` with content
```xml
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
  "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="%userid%">
   <allow own="org.bluez"/>
    <allow send_destination="org.bluez"/>
    <allow send_interface="org.bluez.GattCharacteristic1"/>
    <allow send_interface="org.bluez.GattDescriptor1"/>
    <allow send_interface="org.freedesktop.DBus.ObjectManager"/>
    <allow send_interface="org.freedesktop.DBus.Properties"/>
  </policy>
</busconfig>
```

**Comment by NikeLaosClericus** [comment]
Wow, yeah, that looks to have fixed ble discovery for me.
Now I just see pages of `No tiles found in [...long list of ids...]`
But that does mean it's finding other Bluetooth devices, so node-ble is working for me!

On the side note, my tile pro 2022 is sitting next to my laptop, is there something special I'm supposed to do to find it?

**Comment by lesleyxyz** [comment]
Is your Tile linked to your account? Does it print your Tile in the console with the ID and AuthKey?

The first 12 letters/numbers of the Tile ID should be the bluetooth mac address of your tile. (Case insensitive). Do you see that in the list of mac addresses it prints?

**Comment by NikeLaosClericus** [comment]
Yes, linked to the account and is printed with an ID and AuthKey, name matches what I set for it, productCode: 'OAKLEY_ST1'.
But, and I verified this with the AirGuard App, no part of the reported Tile ID matches the MAC Address of my tile.
Trying to manually verify with bluetoothctl, I don't see any BT devices with a matching MAC to the reported TileID.
I also do not have anti-theft mode enabled on my account.

**Comment by NikeLaosClericus** [comment]
I figured it out!
For whatever reason, the first digit is mangled in the Tile ID.
eg, instead of a TileID of AA AA AA AA AA AA XX XX, matching my Tile's MAC of AA...AA, the Tile ID is
BA AA AA AA AA AA XX XX!

Specifically, my Tile's ID starts with 49, but my Tile's actual MAC starts C9.

I can get around that by using .slice(1):
```
async function getATile(tiles){
	while(true){
		const bleUuids = await adapter.devices()
		for(let bleUuid of bleUuids){
			let bleUuidConverted = bleUuid.split(":").join("").slice(1).toLowerCase()
			let tile = tiles.filter(t => t.id.slice(1).startsWith(bleUuidConverted))[0]
			if(tile){
				return [bleUuid, tile]
			}
		}
		console.log("No tiles found in", bleUuids)
		await sleep(1000)
	}
}
```

**Comment by NikeLaosClericus** [comment]
The ringer going off both terrified and relieved me.
Thank you very much for helping me with this.

**Comment by lesleyxyz** [comment]
I'm glad it worked :) For my tiles this wasn't the case so interesting.. I'll change it in the example thanks!
